// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eralmzpuepbzvzoyzecz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyYWxtenB1ZXBienZ6b3l6ZWN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjkwNDAsImV4cCI6MjA2MDkwNTA0MH0.Q0hdALAukscEIAoNnwCUfPbsP0sRKLZkzjDysBSWFkc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);